Cookies session
NecroSith/film-database pull request #4
Opened 2018-06-30 20:23 UTC by NecroSith

Пароль и логин админа прописаны в БД, реализована проверка в функции adminNameCheck в films.php

2018-07-02 10:40 UTC, nobleworkshop requested changes
Надо добавить новый дамп БД с таблицей данных пользователя. Сейчас такой нет.

2018-07-02 10:40 UTC, nobleworkshop commented on views/index.tpl
> +          <img height=200 src="<?=HOST?>data/films/min/<?=$films[$key]['image']?>" alt="<?php echo $films[$key]['name'];?>">
В цикле выше мы уже получаем каждый отдельный фильм в $value
Не надо писать через $films[$key]['image']
Можно и нужно писать сразу $value['image']

И в цикле стоит писать 
foreach ($films as $film) {

или 
foreach ($films as $key => $film) {
если хочется иметь индекс.

2018-07-02 10:40 UTC, nobleworkshop commented on films.php
> +function adminNameCheck($connect) {
Функции связанные с логином надо вынести в отдельный файл.
К films они никакого отношения не имеют.

2018-07-02 11:01 UTC, NecroSith commented
Недочеты исправлены

2018-07-02 11:03 UTC, NecroSith commented
Добавлен свежий дамп ДБ

2018-07-02 11:04 UTC, NecroSith commented on films.php
> +function adminNameCheck($connect) {
Исправлено, перенесено в login_functions.php

2018-07-02 11:04 UTC, NecroSith commented on views/index.tpl
> +          <img height=200 src="<?=HOST?>data/films/min/<?=$films[$key]['image']?>" alt="<?php echo $films[$key]['name'];?>">
Исправлено

2018-07-04 20:35 UTC, nobleworkshop approved these changes
За куки и авторизацию и сессии зачет.
Но!
Удаление поломалось.
На странице ввести информацию (город, имя) - сессии уже не работают. Будьте внимательны. Когда что то добавляете, остальное должно продолжать работать.

2018-07-04 22:32 UTC, NecroSith commented
Это недопустимо. Я пофиксил удаление фильмов, теперь все хорошо. Сессии тоже будут исправлены в ближайшее время.

2018-07-05 17:09 UTC, NecroSith commented
Проблема с сессией была решена - теперь все работает нормально

2018-07-16 12:00 UTC, nobleworkshop commented
@NecroSith Теперь работает корректно!) Отлично)

2018-07-16 12:01 UTC, nobleworkshop approved these changes

2018-07-16 14:11 UTC, merged